### ISSUE TITLE
[JENKINS-25442] Warnings plugin gives exception since upgrading to Jenkins 1.588

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/warnings-ng-plugin#2517]
<p>Since upgrading from Jenkins 1.584 to 1.588 and upgrading Warnings plugin from 4.42 to 4.43, I now see the following exception:</p>

<table><tr><td><p><span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser GNU C Compiler 4 (gcc)<br/>
ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception<br/>
java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V<br/>
	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)<br/>
	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)<br/>
	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)<br/>
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)<br/>
	at hudson.model.Build$BuildExecution.post2(Build.java:183)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)<br/>
	at hudson.model.Run.execute(Run.java:1784)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:89)<br/>
	at hudson.model.Executor.run(Executor.java:240)</p></td></tr></table>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=davida2009">davida2009</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25442" target="_blank">Warnings plugin gives exception since upgrading to Jenkins 1.588</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/drulli.png" title="drulli's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: warnings-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-11-05T11:00:03+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-09
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Since upgrading from Jenkins 1.584 to 1.588 and upgrading Warnings plugin from 4.42 to 4.43, I now see the following exception:</p>

<div class="panel" style="border-width: 1px;"><div class="panelContent">
<p><span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser GNU C Compiler 4 (gcc)
ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception
java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V
	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)
	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)
	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)</p>
</div></div></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>davida2009:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25442?focusedId=215462&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-215462">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I downgraded to Jenkins 1.584 and Warnings 4.42 and found that the exception still occurs. I upgraded quite a few other plugins when I upgraded to Warnings 4.43, so perhaps the problem is with one of those, but I don't know which one.</p>
</pre>
</details>

</ul>
</details>

<p>I downgraded to Jenkins 1.584 and Warnings 4.42 and found that the exception still occurs. I upgraded quite a few other plugins when I upgraded to Warnings 4.43, so perhaps the problem is with one of those, but I don't know which one.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>baranyaib90:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25442?focusedId=215464&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-215464">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Same thing here!
Please fix it!</p>
</pre>
</details>

</ul>
</details>

<p>Same thing here!<br/>
Please fix it!</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25442?focusedId=215467&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-215467">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>As the linked issue indicates, you need to downgrade analysis-core ("Static Analysis" I think it's called) to 1.62, or upgrade to 1.65 if it exists already.</p>
</pre>
</details>

</ul>
</details>

<p>As the linked issue indicates, you need to downgrade analysis-core ("Static Analysis" I think it's called) to 1.62, or upgrade to 1.65 if it exists already.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>davida2009:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25442?focusedId=215469&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-215469">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Thanks, upgrading to Static Analysis plugin 1.65 fixed the problem.</p>
</pre>
</details>

</ul>
</details>

<p>Thanks, upgrading to Static Analysis plugin 1.65 fixed the problem.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/25405">JENKINS-25405</a>]</i>
