### ISSUE TITLE
[JENKINS-25447] ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/warnings-ng-plugin#2518]
<p>After updating "warnings-plugin" from 4.42 to 4.43 (and "analysis-core" from 1.61 to 1.64) then ALL my jobs fail no matter which parser is used (see logs below).</p>

<p>I tried to downgrade "warnings-plugin" to 4.42, still they fail.<br/>
I tried to uninstall "warnings-plugin" and install it again, still they fail.<br/>
I tried to disable "warnings-plugin" in the individual job (they pass, obviously) and enable it again, still they fail.</p>

<p>Then I tried to downgrade "analysis-core" to 1.61, and they pass again.<br/>
So, seems to be an issue with "analysis-core" 1.64.</p>

<p>Log example 1:</p>

<blockquote>
<p>00:02:46.430 <span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser IAR Compiler (C/C++)<br/>
00:02:46.491 ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception<br/>
00:02:46.494 java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V<br/>
00:02:46.495 	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)<br/>
00:02:46.495 	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)<br/>
00:02:46.495 	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)<br/>
00:02:46.495 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
00:02:46.495 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)<br/>
00:02:46.495 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)<br/>
00:02:46.495 	at hudson.model.Build$BuildExecution.post2(Build.java:182)<br/>
00:02:46.495 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)<br/>
00:02:46.495 	at hudson.model.Run.execute(Run.java:1731)<br/>
00:02:46.495 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
00:02:46.495 	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
00:02:46.495 	at hudson.model.Executor.run(Executor.java:232)</p></blockquote>

<p>Log example 2:</p>

<blockquote>
<p>00:03:34.271 <span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser Texas Instruments Code Composer Studio (C/C++)<br/>
00:03:34.286 ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception<br/>
00:03:34.286 java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V<br/>
00:03:34.286 	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)<br/>
00:03:34.286 	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)<br/>
00:03:34.286 	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)<br/>
00:03:34.286 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
00:03:34.286 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)<br/>
00:03:34.286 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)<br/>
00:03:34.287 	at hudson.model.Build$BuildExecution.post2(Build.java:182)<br/>
00:03:34.287 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)<br/>
00:03:34.287 	at hudson.model.Run.execute(Run.java:1731)<br/>
00:03:34.287 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
00:03:34.287 	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
00:03:34.287 	at hudson.model.Executor.run(Executor.java:232)</p></blockquote>

<p>Log example 3:</p>

<blockquote>
<p>00:01:56.629 <span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser MSBuild<br/>
00:01:56.644 ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception<br/>
00:01:56.645 java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V<br/>
00:01:56.645 	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)<br/>
00:01:56.645 	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)<br/>
00:01:56.645 	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)<br/>
00:01:56.645 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
00:01:56.645 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)<br/>
00:01:56.645 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)<br/>
00:01:56.645 	at hudson.model.Build$BuildExecution.post2(Build.java:182)<br/>
00:01:56.645 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)<br/>
00:01:56.646 	at hudson.model.Run.execute(Run.java:1731)<br/>
00:01:56.646 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
00:01:56.646 	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
00:01:56.646 	at hudson.model.Executor.run(Executor.java:232)</p></blockquote>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jonasbang">jonasbang</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25447" target="_blank">ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/drulli.png" title="drulli's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>component(s)</b>: analysis-core-plugin, warnings-plugin
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2014-11-05T12:09:14+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-09
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After updating "warnings-plugin" from 4.42 to 4.43 (and "analysis-core" from 1.61 to 1.64) then ALL my jobs fail no matter which parser is used (see logs below).</p>

<p>I tried to downgrade "warnings-plugin" to 4.42, still they fail.
I tried to uninstall "warnings-plugin" and install it again, still they fail.
I tried to disable "warnings-plugin" in the individual job (they pass, obviously) and enable it again, still they fail.</p>

<p>Then I tried to downgrade "analysis-core" to 1.61, and they pass again.
So, seems to be an issue with "analysis-core" 1.64.</p>

<p>Log example 1:</p>

<blockquote>
<p>00:02:46.430 <span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser IAR Compiler (C/C++)
00:02:46.491 ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception
00:02:46.494 java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V
00:02:46.495 	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)
00:02:46.495 	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)
00:02:46.495 	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)
00:02:46.495 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
00:02:46.495 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
00:02:46.495 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
00:02:46.495 	at hudson.model.Build$BuildExecution.post2(Build.java:182)
00:02:46.495 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
00:02:46.495 	at hudson.model.Run.execute(Run.java:1731)
00:02:46.495 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:02:46.495 	at hudson.model.ResourceController.execute(ResourceController.java:88)
00:02:46.495 	at hudson.model.Executor.run(Executor.java:232)</p></blockquote>

<p>Log example 2:</p>

<blockquote>
<p>00:03:34.271 <span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser Texas Instruments Code Composer Studio (C/C++)
00:03:34.286 ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception
00:03:34.286 java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V
00:03:34.286 	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)
00:03:34.286 	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)
00:03:34.286 	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)
00:03:34.286 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
00:03:34.286 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
00:03:34.286 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
00:03:34.287 	at hudson.model.Build$BuildExecution.post2(Build.java:182)
00:03:34.287 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
00:03:34.287 	at hudson.model.Run.execute(Run.java:1731)
00:03:34.287 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:03:34.287 	at hudson.model.ResourceController.execute(ResourceController.java:88)
00:03:34.287 	at hudson.model.Executor.run(Executor.java:232)</p></blockquote>

<p>Log example 3:</p>

<blockquote>
<p>00:01:56.629 <span class="error">&#91;WARNINGS&#93;</span> Parsing warnings in console log with parser MSBuild
00:01:56.644 ERROR: Publisher hudson.plugins.warnings.WarningsPublisher aborted due to exception
00:01:56.645 java.lang.NoSuchMethodError: hudson.plugins.analysis.core.ParserResult.addAnnotations(Ljava/util/Collection;)V
00:01:56.645 	at hudson.plugins.warnings.WarningsPublisher.parseConsoleLog(WarningsPublisher.java:405)
00:01:56.645 	at hudson.plugins.warnings.WarningsPublisher.perform(WarningsPublisher.java:321)
00:01:56.645 	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:319)
00:01:56.645 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
00:01:56.645 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
00:01:56.645 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
00:01:56.645 	at hudson.model.Build$BuildExecution.post2(Build.java:182)
00:01:56.645 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
00:01:56.646 	at hudson.model.Run.execute(Run.java:1731)
00:01:56.646 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:01:56.646 	at hudson.model.ResourceController.execute(ResourceController.java:88)
00:01:56.646 	at hudson.model.Executor.run(Executor.java:232)</p></blockquote></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins ver. 1.565.3</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>jonasbang:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25447?focusedId=215471&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-215471">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Just to make it perfectly clear:
It works now with "warnings-plugin" 4.43 and "analysis-core" 1.61 on Jenkins 1.565.3</p>
</pre>
</details>

</ul>
</details>

<p>Just to make it perfectly clear:<br/>
It works now with "warnings-plugin" 4.43 and "analysis-core" 1.61 on Jenkins 1.565.3</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25447?focusedId=215473&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-215473">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Duplicates ... some other issue I can't be bothered to search right now <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>Solution: Update Analysis Core to 1.65. (Plugin Manager » Advanced » Check Now to force a refresh of the data)</p>
</pre>
</details>

</ul>
</details>

<p>Duplicates ... some other issue I can't be bothered to search right now <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>Solution: Update Analysis Core to 1.65. (Plugin Manager » Advanced » Check Now to force a refresh of the data)</p>
